[package]
name = "akiraka"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
#druid = "0.8.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.5"


[profile.release]
opt-level = 'z'