[package]
name = "akiraka"
version = "0.1.0"
edition = "2021"
[target.'cfg(windows)'.build-dependencies]
build = "build.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.5"
rust-embed="6.6.1"
#druid = "0.8.3"
image = "0.24.6"
[target.'cfg(windows)'.build-dependencies]
windres = "0.2"

[profile.release]
opt-level = 'z'