[package]
name = "akiraka-core"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.5"
sysinfo = "0.29.0"
zip = "0.6.2"